#!/usr/bin/env bash

workspaces() {
  ws=("1" "2" "3" "4" "5")
  un="0"
  icons=("" "" "" "" "")

  # focused_ws=$(bspc query -D -d focused --names)

  for i in "${!ws[@]}"; do
    occupied=$(bspc query -D -d .occupied --names | grep "${ws[$i]}")
    focused=$(bspc query -D -d focused --names | grep "${ws[$i]}")

   # if [ "$occupied" == "${ws[$i]}" ]; then
   #    icons[$i]="A"
   #  fi
    if [ "$focused" == "${ws[$i]}" ]; then
      icons[$i]=""
    fi

    echo -n "(button :onclick \"bspc desktop -f ${ws[$i]}\" :class \"$un$occupied$focused\" \"${icons[$i]}\")"
  done

}
run() {
  echo "(box :class \"works\" :orientation \"v\" :spacing 5 :space-evenly \"false\" $(workspaces))"
}

run
bspc subscribe desktop node_transfer | while read -r _; do
  run
done

